query users {
  users {
    data {
      _id
      name
      email
      password
    }
  }
}
query findUserEntryByID($id: ID!) {
  findUserEntryByID(id: $id) {
    _id
    name
    email
    password
    _ts
  }
}
query findUserEntryByEmail($email: String!) {
  findUserEntryByEmail(email: $email) {
    _id
    email
    name
    password
    isVerifiedEmail
    _ts
  }
}
mutation createUserEntry(
  $email: String!
  $name: String
  $password: String!
  $isVerifiedEmail: Boolean!
) {
  createUserEntry(
    data: { email: $email, name: $name, password: $password, isVerifiedEmail: $isVerifiedEmail }
  ) {
    _id
    email
    name
    isVerifiedEmail
  }
}
mutation updateIsVerifiedEmailUserEntry($id: ID!, $isVerifiedEmail: Boolean!) {
  updateUserEntry(id: $id, data: { isVerifiedEmail: $isVerifiedEmail }) {
    _id
    email
    name
    isVerifiedEmail
  }
}
mutation updatePasswordUserEntry($id: ID!, $password: String!) {
  updateUserEntry(id: $id, data: { password: $password }) {
    _id
    email
    name
    isVerifiedEmail
  }
}
